# Generated by Django 3.2.3 on 2024-05-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20210524_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.AddField(
            model_name='product',
            name='ama_discount_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='ama_market_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='ama_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='new_product_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='product',
            name='timestamp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='articel_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender_cat',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='market_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_cat',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
